### ISSUE TITLE
Make toolbar icons easier to click + add tooltips and "button shape" UI feedback when hovering

### ISSUE THREAD

**Issue by rxhfcy** [Moonif/MacBox#12]
**Is your feature request related to a problem? Please describe.**
I just installed MacBox for the first time ever, and noticed some unnecessary "friction" when trying to click a toolbar icon:
1) I tried to "Add VM" ("+") but my click was silently discarded (because the "hitbox" of the button is way too small: technically my mouse cursor was actually hovering over the text "Add VM" but that shouldn't matter)
2) I was also expecting a tooltip to appear when hovering over the button(s) (even though there's already some text e.g. "Add VM")
3) Also, there was no visual feedback when hovering over the button(s): the normal "button shape" UI feedback didn't appear

**Describe the solution you'd like**
1) Make the "hitboxes" much bigger to make it easier to click them (see mockup / screenshot further below)
2) Add descriptive tooltips when hovering over the button(s) (for example: I can only guess what "Printer Tray" might mean in this context, and the same goes for "Screenshots")
- tooltip: "Create or Import a Virtual Machine"
- tooltip: "Show Printer Tray for selected Virtual Machine" (??)
- tooltip: "Show Screenshots Folder in Finder" (??)
3) Show visual UI feedback when hovering over the button(s) (i.e. show "button shape", see screen recording + screenshot further below)

**Describe alternatives you've considered**
I guess the alternative is to not do anything, but I honestly can't see any downside to making these tweaks.

**Additional context**
Mockups / screenshots:
1) Make the "hitboxes" much bigger, also allow clicking on the text etc:

<img width="725" alt="hitboxes" src="https://github.com/Moonif/MacBox/assets/42669366/ce10dd26-107d-4959-ae9c-284b7bb5783b">

3) Example screen recording of the "button shape" UI feedback that appears in other applications when hovering over toolbar buttons (example from Finder.app)

https://github.com/Moonif/MacBox/assets/42669366/07e80307-d8e3-45c0-a2bb-fb44ab8597e2

Screenshot of the same thing:

<img width="454" alt="button_shape" src="https://github.com/Moonif/MacBox/assets/42669366/1984cd6b-2959-4098-a57e-df465da230e2">

**Comment by Moonif** [comment]
Fixed in version 0.4.6
