### ISSUE TITLE
Please don't add a directory to ~ by default (don't clutter the user's home directory)

### ISSUE THREAD

**Issue by rxhfcy** [Moonif/MacBox#16]
**Is your feature request related to a problem? Please describe.**
Adding directories straight to /Users/username (i.e. the user's home directory) should be avoided at all cost, especially on macOS. Applications should never add anything straight to ~ unless explicitly requested by the user.

Just think of what would happen if every macOS application added their own stuff straight to /Users/username by default (yuck)

**Describe the solution you'd like**
Please use ~/Library/whatever (or /Applications!), or almost anything else. The user's Unix home directory should remain uncluttered.

**Describe alternatives you've considered**
I haven't used MacBox (or 86Box) enough to understand what might have been the motivation to use ~ by default instead of e.g. /Applications or /Library/whatever. I'm already pretty sure I wouldn't be convinced by the (technical?) reason though. :)

I really hope this is at least just a temporary hack/workaround, and that things will be fixed in the future.

**Additional context**
Even Linux applications don't do this. I found issues like this for other projects too, but I don't think it would be tactful or relevant to add links here.

**Comment by Moonif** [comment]
Added as an option in version 0.4.8

**Comment by bestlem** [comment]
How do you set this - the file open dialog does not change the open button to something that works + it has no New Folder button

**Comment by Moonif** [comment]
> How do you set this - the file open dialog does not change the open button to something that works + it has no New Folder button

From the Settings menu, "MacBox" section -> Path -> Custom
