### ISSUE TITLE
Change keys for mouse capturing

### ISSUE THREAD

**Issue by Alexco500** [Moonif/MacBox#17]
It would be great if you could change the key combo for capture/free the mouse. I am using MacBox on my Laptop and the default keys are hard to find :-)
Maybe there is an option for that in 86box.

**Comment by Moonif** [comment]
Hi Alexco500,

I'm not one of the 86Box devs, so I can't really do anything about that, but I suggest posting this feedback on the 86Box Github page: [https://github.com/86Box/86Box/issues](https://github.com/86Box/86Box/issues)

Or via their Discord server: [https://discord.gg/v5fCgFw](https://discord.gg/v5fCgFw)

**Comment by Alexco500** [comment]
Ah, ok, I will do that.
