### ISSUE TITLE
86Box could not find any usable ROM images.

### ISSUE THREAD

**Issue by jamonholmgren** [Moonif/MacBox#2]
I'm trying to figure out why 86box won't run. I get this error:

```
86Box could not find any usable ROM images. Please [download](https://github.com/86Box/roms/releases/latest) a ROM set and extract it into the "roms" directory.
```

<img width="817" alt="CleanShot 2023-11-05 at 16 23 12@2x" src="https://github.com/Moonif/MacBox/assets/1479215/cf82a9b5-d66f-4d9c-b447-861a217f5e2a">

But ... I'm not really sure where to put this. What folder do I download the ROM into?

**Comment by jamonholmgren** [comment]
Ah, never mind. Figured it out!

Just needed to download it and extract it directly into this folder (which I created):

`/Users/<myusername>/MacBox/roms`

<img width="223" alt="CleanShot 2023-11-05 at 16 25 02@2x" src="https://github.com/Moonif/MacBox/assets/1479215/a9a08614-a2f9-4695-a7e8-1c9eda41a0e4">

**Comment by Moonif** [comment]
Actually, if you want the roms folder to work for all of your VM's, it's better to put it in the library folder (ex: /Library/Application Support/net.86box.86Box/roms)

Check out the documation for more info: https://86box.readthedocs.io/en/latest/usage/roms.html
