### ISSUE TITLE
Cannot Install 86Box from Main View (Mac OS)

### ISSUE THREAD

**Issue by geeksweep** [Moonif/MacBox#24]
**Describe the bug**
When launching the app, i was able to install the Rom Updates but when installed 86Box nothing happens. (see screenshot)

**To Reproduce**
1. Run/Launch app
2. Tap 'Run' button to install 86Box

Machine Specs: 

Macbook Pro
Apple M1 Max, 64 GB 
Ventura 13.6.4

**Expected behavior**

Expecting to install 86Box

<img width="435" alt="Screenshot 2024-06-20 at 8 06 39 PM" src="https://github.com/Moonif/MacBox/assets/1126840/db2cd13c-2c9e-4e61-9166-0432015f6c84">

**Comment by Moonif** [comment]
It's probably a connection issue with the 86Box beta website, can you try switching the update channel to **stable** and see if the 86Box download works for you? (MacBox -> Settings... -> Update Channel)

**Comment by geeksweep** [comment]
> It's probably a connection issue with the 86Box beta website, can you try switching the update channel to **stable** and see if the 86Box download works for you? (MacBox -> Settings... -> Update Channel)

Thanks that seemed to work. Is there any particular setup to make the boot disk run? i keep getting a "disk boot failure , insert system disk and press Enter. " running Compaq Presario 1997, 3dfx voodoo PCI
