### ISSUE TITLE
Make MacBox work on 10.15

### ISSUE THREAD

**Issue by jvernet** [Moonif/MacBox#27]
The previous version was working under MacOs 10.15, but ask now for MacOs 11 minimum. My MacBook Pro can't pass 10.15...

I tried to build MacBox myself without success with XCode 12.4.

Thanks in advance !

**Comment by Moonif** [comment]
Thanks for reporting!
It seems Xcode 16 automatically sets the minimum deployment version to Big Sur, I manually set it back to 10.14.
Hopefully this will fix the issue.

**Comment by jvernet** [comment]
It's working, thanks !
Nice job, the bet fontend for 86Box
