### ISSUE TITLE
Settings -> Hard Disks

### ISSUE THREAD

**Issue by rrcoley** [Moonif/MacBox#4]
**Is your feature request related to a problem? Please describe.**
It's frustrating that you can't see the disk name clearly.  I have to try shrinking the header panes but then i can't see the ID and the the size etc...
<img width="796" alt="PastedGraphic-1" src="https://github.com/Moonif/MacBox/assets/66431497/ce3eee38-72d2-42ea-8d8d-da6852879ca2">

**Describe the solution you'd like**
Well im guessing at some point there needs to be an option here to denote LBA and not just CHS - so the panel will get wider... perhaps horizontal scrollbar although i cringe as I suggest it.  Perhaps you just show the final part of the pathname, and allow you to double lclick on this to get a popup with full pathname??

By the way - think its great, makes using 86box much easier

**Comment by Moonif** [comment]
Hello,

Since this isn't a MacBox issue, I can't really help as I'm not one of the 86Box developers.
I suggest posting your issue to the 86Box GitHub page: [86Box](https://github.com/86Box/86Box)
