### ISSUE TITLE
New release box returns immediately after clicking "dismiss"

### ISSUE THREAD

**Issue by keaaw** [Moonif/MacBox#7]
Running MacBook 0.3.8, today a new release became available (apparently!) and the new release alert box comes up.  Clicking "dismiss" closes the box, but it instantly reappears.   This happened about 10 times in a row.    After quitting and restarting MacBox, the same behavior ocurred, but less frequently.    Finally, it seems to only appear once per run on startup, but then the version check seems to re-run and it pops up again some time later.

One click of "dismiss" per invocation should be enough :).

**To Reproduce**
Have MacBox open when a new release comes available.

**Expected behavior**
Clicking "dismiss" should prevent this dialog from appearing for the lifetime of the current invocation, or at least, for a good long time (or maybe ask for "remind me in X days", or offer "never ask again for this version", etc.).

**Comment by Moonif** [comment]
Hello,

Thank you for reporting this issue, it sure sounds annoying!

Unfortunately, I can't seem to reproduce it, but I'm working on a "Skip this version" option anyway, and hopefully it will be available very soon.

**Comment by keaaw** [comment]
OK So the issue reproduces for me under XCode 15.1 on Ventura 13.5.2.   It's easy to reproduce: just toggle on or off a VPN connection and the InternetConnectionMonitor fires..    I see in XCode what is happening, but am not up on latest mac programming so don't know exactly why.   You're getting multiple threads running your InternetConnectionMonitor simultaneously.  They're being launched by 
 the com.apple.network.connections thread.   Over time these threads build up and you get multiple launches of the Monitor, which explains the multiple dialog boxes.   So debugging this is needed, just changing settings won't help, you've got an async/thread multiplication issue here.   perhaps deleting the monitor once it runs once would do it.   But something is continuing to fire off this monitor over and over in new threads and that is the key issue.

**Comment by Moonif** [comment]
Nice catch! I was able to reproduce it by turning on/off my wifi.

And indeed, cancelling the monitor fixed the issue. Thanks for the help!

**Comment by Moonif** [comment]
Fixed in 0.4
