### ISSUE TITLE
MacBox can't find my virtual machine

### ISSUE THREAD

**Issue by Schnubbirunkel** [Moonif/MacBox#8]
For some reason, MacBox can't find my virtual machine. It searches everywhere, but nothing pops up. I've tried to add it myself, but I have no idea what files it is looking for and where to find them.
Any ideas, what I'm doing wrong?

**Comment by Moonif** [comment]
Hello,

MacBox looks for the 86Box cfg file (86box.cfg), how does your VM folder look like? Does it have the cfg file and the nvr folder?

**Comment by Schnubbirunkel** [comment]
Hmm, I can only find the IMG file from my virtual harddrive. Maybe the config files get stored somewhere else, and I messed something up when creating the VM?

**Comment by Schnubbirunkel** [comment]
Ahhh! Nevermind, I found the config file in the Applications folder for some reason. Big thanks for the filename!

**Comment by Moonif** [comment]
No problem, glad it worked out. 👍
